// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
	"time"
)

type Todo struct {
	ID        int32        `json:"id"`
	Title     string       `json:"title"`
	UserID    int32        `json:"user_id"`
	Finished  bool         `json:"finished"`
	Deadline  sql.NullTime `json:"deadline"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

type User struct {
	ID                int32     `json:"id"`
	Email             string    `json:"email"`
	EncryptedPassword string    `json:"encrypted_password"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}
